[package]
name = "gif-displayer"
version = "0.1.0"
authors = ["peaBerberian <pea.berberian@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lzw = "0.10.0"
